services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./trading:/trading
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8000"