services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database
      - DB_USER=dbuser
      - DB_NAME=dbname
      - DB_PASS=pass
    ports:
      - "8000:8000"
    volumes:
      - ./trading:/trading
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8000"

    depends_on:
      - database
  

  database:
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass